#!/usr/bin/env node
/**
 * Postbuild: compute SHA-256 hashes of every inline <script> block in
 * dist/**\/*.html and emit dist/_headers with a strict CSP that allows
 * exactly those hashes. Output is `_headers`-format (Netlify), which
 * takes precedence over the netlify.toml header for the same path.
 *
 * The point: drop 'unsafe-inline' from script-src so JSON-LD can ship
 * without a blanket script execution waiver. Inline blocks ride on
 * 'sha256-*' hashes; any out-of-band script (XSS injection) won't match.
 *
 * Style-src keeps 'unsafe-inline' — Vite occasionally emits a style
 * attribute (the noscript fallback uses one), and the impact of inline
 * styles is much lower than inline scripts. Hardening style-src is
 * deferred until that's the cheapest remaining win.
 */
import { readFile, writeFile, readdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(__dirname, "..", "dist");

async function* walkHtml(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walkHtml(full);
    else if (entry.isFile() && entry.name.endsWith(".html")) yield full;
  }
}

/* Match <script> blocks that have inline content (no src attribute).
   The negative lookahead `(?![^>]*\bsrc\s*=)` skips external scripts.
   Exported for testing — the postbuild check is the regression net for
   "Vite started emitting an inline <script> we don't have a hash for". */
export const INLINE_SCRIPT_RE = /<script(?![^>]*\bsrc\s*=)[^>]*>([\s\S]*?)<\/script>/gi;

/** Extract the inline content of every non-src <script> in `html`. */
export function extractInlineScripts(html) {
  const out = [];
  const re = new RegExp(INLINE_SCRIPT_RE.source, INLINE_SCRIPT_RE.flags);
  let m;
  while ((m = re.exec(html))) {
    if (m[1] && m[1].trim()) out.push(m[1]);
  }
  return out;
}

async function main() {
  const hashes = new Set();
  let pagesScanned = 0;
  let blocksFound = 0;

  for await (const file of walkHtml(DIST)) {
    pagesScanned++;
    const html = await readFile(file, "utf-8");
    for (const content of extractInlineScripts(html)) {
      blocksFound++;
      const hash = createHash("sha256").update(content).digest("base64");
      hashes.add(`'sha256-${hash}'`);
    }
  }

  if (hashes.size === 0) {
    console.error("compute-csp: no inline <script> blocks found — refusing to emit a CSP without hashes (would block JSON-LD).");
    process.exit(1);
  }

  const scriptSrc = ["'self'", "https://plausible.io", ...hashes].join(" ");
  const csp = [
    "default-src 'self'",
    // Explicit: the default-src fallback would otherwise allow same-origin
    // plugin embedding (<object>/<embed>).
    "object-src 'none'",
    `script-src ${scriptSrc}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self' https://app.kaynos.net https://demo.kaynos.net https://student.kaynos.net https://docs.kaynos.net https://plausible.io",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "upgrade-insecure-requests",
  ].join("; ");

  const body = `# Auto-generated by scripts/compute-csp.mjs — do not edit.\n# Regenerated on every build with hashes for the inline JSON-LD scripts in dist/.\n/*\n  Content-Security-Policy: ${csp}\n`;

  await writeFile(join(DIST, "_headers"), body);
  console.log(
    `compute-csp: ${pagesScanned} page${pagesScanned === 1 ? "" : "s"} scanned, ${blocksFound} inline script${blocksFound === 1 ? "" : "s"}, ${hashes.size} unique hash${hashes.size === 1 ? "" : "es"} → dist/_headers`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error("compute-csp: failed");
    console.error(err);
    process.exit(1);
  });
}
